// parkWise_react/parkwise_fe/features/admin/AdminPage.tsx
import { useCallback, useEffect, useState } from "react";
import { AdminReservationRows } from "@/components/bookings/ReservationTable";
import { Button, Card, Stat, Tag } from "@/components/ui";
import { apiErrorMessage, parkwiseApi } from "@/services/parkwiseApi";
import type { AdminStats, Notify, Reservation } from "@/types/parkwise";

export function AdminPage({ notify }: { notify: Notify }) {
  const [stats, setStats] = useState<AdminStats | null>(null);
  const [items, setItems] = useState<Reservation[]>([]);
  const [loading, setLoading] = useState(true);

  const load = useCallback(() => {
    setLoading(true);
    Promise.all([parkwiseApi.adminStats(), parkwiseApi.adminReservations()])
      .then(([statsResponse, reservationResponse]) => {
        setStats(statsResponse);
        setItems(reservationResponse);
      })
      .catch((err) => notify({ severity: "error", summary: "Admin data unavailable", detail: apiErrorMessage(err, "Failed to load admin dashboard.") }))
      .finally(() => setLoading(false));
  }, [notify]);

  useEffect(load, [load]);

  async function cancel(item: Reservation) {
    try {
      const updated = await parkwiseApi.cancelReservation(item.id);
      setItems((current) => current.map((row) => row.id === updated.id ? updated : row));
      notify({ severity: "success", summary: "Booking cancelled", detail: `PKW-${updated.id} was cancelled.` });
    } catch (err) {
      notify({ severity: "error", summary: "Cancellation failed", detail: apiErrorMessage(err, "Could not cancel booking.") });
    }
  }

  const totalRevenue = items.reduce((sum, item) => sum + Number(item.amount || 0), 0);

  return (
    <section className="page-stack">
      <div className="page-title">
        <div><h1>Admin</h1><p>Monitor occupancy, bookings, users, and revenue.</p></div>
        <Button variant="outlined" disabled={loading} onClick={load}>Refresh</Button>
      </div>
      <div className="stat-grid">
        <Stat label="Users" value={stats?.total_users ?? 0} />
        <Stat label="Active bookings" value={stats?.active_bookings ?? 0} tone="info" />
        <Stat label="Occupancy" value={`${stats?.occupancy_percent ?? 0}%`} tone="success" />
        <Stat label="Revenue today" value={`₹${stats?.revenue_today ?? 0}`} />
      </div>
      <Card title={<div className="zone-title"><span>Reservations</span><Tag value={`₹${totalRevenue.toFixed(2)} total listed`} severity="info" /></div>}>
        <AdminReservationRows items={items} loading={loading} onCancel={cancel} />
      </Card>
    </section>
  );
}

// parkwise-frontend/src/pages/AdminPage.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useToast } from 'primevue/usetoast'
import Button from 'primevue/button'
import Card from 'primevue/card'
import Column from 'primevue/column'
import DataTable from 'primevue/datatable'
import Message from 'primevue/message'
import Skeleton from 'primevue/skeleton'
import Tag from 'primevue/tag'
import { adminService } from '@/services/adminService'
import type { AdminStats, Reservation } from '@/types/index'

const toast = useToast()
const stats = ref<AdminStats | null>(null)
const reservations = ref<Reservation[]>([])
const isLoading = ref(true)

const totalRevenue = computed(() => {
  return reservations.value.reduce((sum, reservation) => sum + Number(reservation.amount || 0), 0)
})

function formatDate(value: string) {
  return new Date(value).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' })
}

function statusSeverity(status: Reservation['status']) {
  if (status === 'cancelled') return 'danger'
  if (status === 'completed') return 'success'
  return 'info'
}

async function loadAdminData() {
  isLoading.value = true
  try {
    const [statsResponse, reservationResponse] = await Promise.all([
      adminService.getStats(),
      adminService.getReservations(),
    ])
    stats.value = statsResponse
    reservations.value = reservationResponse
  } catch (error) {
    toast.add({
      severity: 'error',
      summary: 'Admin data unavailable',
      detail: error instanceof Error ? error.message : 'Failed to load admin dashboard.',
      life: 5000,
    })
  } finally {
    isLoading.value = false
  }
}

onMounted(loadAdminData)
</script>

<template>
  <section class="page-stack">
    <div class="page-title">
      <div>
        <h1>Admin</h1>
        <p>Monitor occupancy, bookings, users, and revenue.</p>
      </div>
      <Button icon="pi pi-refresh" label="Refresh" outlined :loading="isLoading" @click="loadAdminData" />
    </div>

    <div class="stat-grid">
      <Card>
        <template #content>
          <span class="muted-label">Users</span>
          <strong class="stat">{{ stats?.total_users ?? 0 }}</strong>
        </template>
      </Card>
      <Card>
        <template #content>
          <span class="muted-label">Active bookings</span>
          <strong class="stat info">{{ stats?.active_bookings ?? 0 }}</strong>
        </template>
      </Card>
      <Card>
        <template #content>
          <span class="muted-label">Occupancy</span>
          <strong class="stat success">{{ stats?.occupancy_percent ?? 0 }}%</strong>
        </template>
      </Card>
      <Card>
        <template #content>
          <span class="muted-label">Revenue today</span>
          <strong class="stat">₹{{ stats?.revenue_today ?? 0 }}</strong>
        </template>
      </Card>
    </div>

    <Card>
      <template #title>
        <div class="zone-title">
          <span>Reservations</span>
          <Tag :value="`₹${totalRevenue.toFixed(2)} total listed`" severity="info" />
        </div>
      </template>
      <template #content>
        <div v-if="isLoading" class="page-stack">
          <Skeleton v-for="index in 5" :key="index" height="3.5rem" />
        </div>
        <Message v-else-if="reservations.length === 0" severity="info" :closable="false">
          No reservations found.
        </Message>
        <DataTable
          v-else
          :value="reservations"
          paginator
          :rows="10"
          :rows-per-page-options="[10, 25, 50]"
          sort-field="created_at"
          :sort-order="-1"
          responsive-layout="scroll"
        >
          <Column field="id" header="ID" sortable>
            <template #body="{ data }">PKW-{{ data.id }}</template>
          </Column>
          <Column field="user.username" header="User" sortable>
            <template #body="{ data }">
              <div class="table-person">
                <strong>{{ data.user?.username ?? '-' }}</strong>
                <span>{{ data.user?.email ?? '' }}</span>
              </div>
            </template>
          </Column>
          <Column field="spot.label" header="Spot" sortable>
            <template #body="{ data }">{{ data.spot.label }} · Zone {{ data.spot.zone }}</template>
          </Column>
          <Column field="vehicle.plate_number" header="Vehicle">
            <template #body="{ data }">{{ data.vehicle?.plate_number ?? '-' }}</template>
          </Column>
          <Column field="start_time" header="Start" sortable>
            <template #body="{ data }">{{ formatDate(data.start_time) }}</template>
          </Column>
          <Column field="end_time" header="End" sortable>
            <template #body="{ data }">{{ formatDate(data.end_time) }}</template>
          </Column>
          <Column field="amount" header="Amount" sortable>
            <template #body="{ data }">₹{{ data.amount }}</template>
          </Column>
          <Column field="status" header="Status" sortable>
            <template #body="{ data }">
              <Tag :value="data.status" :severity="statusSeverity(data.status)" />
            </template>
          </Column>
        </DataTable>
      </template>
    </Card>
  </section>
</template>
